# Generated by Django 4.2.1 on 2023-05-28 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Eye_Image",
            fields=[
                ("eye", models.AutoField(primary_key=True, serialize=False)),
                (
                    "image",
                    models.ImageField(
                        upload_to="static\\db_eyeimages", verbose_name="Image"
                    ),
                ),
                (
                    "hash",
                    models.CharField(max_length=33, verbose_name="MD5 Hash of Image"),
                ),
                (
                    "dt",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date & Time"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User ID",
                    ),
                ),
            ],
            options={"verbose_name": "Eye Image",},
        ),
        migrations.CreateModel(
            name="Wing_Image",
            fields=[
                ("wing", models.AutoField(primary_key=True, serialize=False)),
                (
                    "image",
                    models.ImageField(
                        upload_to="static\\db_wingimages", verbose_name="Image"
                    ),
                ),
                (
                    "hash",
                    models.CharField(max_length=33, verbose_name="MD5 Hash of Image"),
                ),
                (
                    "dt",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date & Time"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User ID",
                    ),
                ),
            ],
            options={"verbose_name": "Wing Image",},
        ),
        migrations.CreateModel(
            name="w_shape",
            fields=[
                ("wshape", models.AutoField(primary_key=True, serialize=False)),
                ("ws_pred", models.CharField(max_length=10, verbose_name="Prediction")),
                (
                    "ws_normal_prob",
                    models.FloatField(
                        max_length=100, verbose_name="Probability % of Normal"
                    ),
                ),
                (
                    "ws_mutated_prob",
                    models.FloatField(
                        max_length=100, verbose_name="Probability % of Mutant"
                    ),
                ),
                (
                    "ws_o_img",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Droso.wing_image",
                        verbose_name="Original Image ID",
                    ),
                ),
            ],
            options={"verbose_name": "Wing Shape",},
        ),
        migrations.CreateModel(
            name="w_dimen",
            fields=[
                ("wdimen", models.AutoField(primary_key=True, serialize=False)),
                (
                    "wd_area",
                    models.FloatField(max_length=100, verbose_name="Wing overall Area"),
                ),
                (
                    "wd_peri",
                    models.FloatField(
                        max_length=100, verbose_name="Wing overall Perimeter"
                    ),
                ),
                (
                    "wd_o_img",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Droso.wing_image",
                        verbose_name="Original Image ID",
                    ),
                ),
            ],
            options={"verbose_name": "Wing Dimension",},
        ),
        migrations.CreateModel(
            name="w_bristles",
            fields=[
                ("wbrisltes", models.AutoField(primary_key=True, serialize=False)),
                (
                    "bristle_count",
                    models.IntegerField(verbose_name="Wing overall Bristles"),
                ),
                (
                    "wb_o_img",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Droso.wing_image",
                        verbose_name="Original Image ID",
                    ),
                ),
            ],
            options={"verbose_name": "Wing Bristle",},
        ),
        migrations.CreateModel(
            name="Feedback_wing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("A", "Very Satisfied"),
                            ("B", "Somewhat Satisfied"),
                            ("C", "Not Satisfied"),
                        ],
                        max_length=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("module", models.CharField(max_length=50)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Droso.wing_image",
                        verbose_name="Image",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feedback_eye",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("A", "Very Satisfied"),
                            ("B", "Somewhat Satisfied"),
                            ("C", "Not Satisfied"),
                        ],
                        max_length=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("module", models.CharField(max_length=50)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Droso.eye_image",
                        verbose_name="Image",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="e_ommatidium",
            fields=[
                ("emodel", models.AutoField(primary_key=True, serialize=False)),
                (
                    "ommatidium_count",
                    models.IntegerField(verbose_name="Eye overall Ommatidium"),
                ),
                (
                    "eo_o_img",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Droso.eye_image",
                        verbose_name="Original Image ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Eye Ommatidium",
                "verbose_name_plural": "Eye Ommatidium",
            },
        ),
        migrations.CreateModel(
            name="e_dimension",
            fields=[
                ("edimension", models.AutoField(primary_key=True, serialize=False)),
                (
                    "earea",
                    models.FloatField(max_length=100, verbose_name="Eye overall Area"),
                ),
                (
                    "eperimeter",
                    models.FloatField(
                        max_length=100, verbose_name="Eye overall Perimeter"
                    ),
                ),
                (
                    "ed_o_img",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Droso.eye_image",
                        verbose_name="Original Image ID",
                    ),
                ),
            ],
            options={"verbose_name": "Eye Dimension",},
        ),
        migrations.CreateModel(
            name="e_colour",
            fields=[
                ("ecolour", models.AutoField(primary_key=True, serialize=False)),
                (
                    "c1_hex",
                    models.CharField(max_length=100, verbose_name="Colour 1 Hex Value"),
                ),
                (
                    "c2_hex",
                    models.CharField(max_length=100, verbose_name="Colour 2 Hex Value"),
                ),
                (
                    "c3_hex",
                    models.CharField(max_length=100, verbose_name="Colour 3 Hex Value"),
                ),
                (
                    "c4_hex",
                    models.CharField(max_length=100, verbose_name="Colour 4 Hex Value"),
                ),
                ("c1_p", models.FloatField(max_length=100, verbose_name="Colour 1 %")),
                ("c2_p", models.FloatField(max_length=100, verbose_name="Colour 2 %")),
                ("c3_p", models.FloatField(max_length=100, verbose_name="Colour 3 %")),
                ("c4_p", models.FloatField(max_length=100, verbose_name="Colour 4 %")),
                (
                    "c1_name",
                    models.CharField(max_length=100, verbose_name="Colour 1 name"),
                ),
                (
                    "c2_name",
                    models.CharField(max_length=100, verbose_name="Colour 2 name"),
                ),
                (
                    "c3_name",
                    models.CharField(max_length=100, verbose_name="Colour 3 name"),
                ),
                (
                    "c4_name",
                    models.CharField(max_length=100, verbose_name="Colour 4 name"),
                ),
                (
                    "pred_name",
                    models.CharField(max_length=10, verbose_name="Predicted Colour"),
                ),
                (
                    "pred_hex",
                    models.CharField(
                        max_length=100, verbose_name="Predicted COlour Hex Value"
                    ),
                ),
                (
                    "ec_o_img",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Droso.eye_image",
                        verbose_name="Original Image ID",
                    ),
                ),
            ],
        ),
    ]
